refactoring Value interface
Wappsto/javascript-wappsto-wapp pull request #66
Opened 2022-04-22 06:28 UTC by sigidagi

Some functionality to remove C style unions and use Typescript discriminated unions/algebraic data types.

2022-04-25 06:58 UTC, AndreasBomholtz requested changes

2022-04-25 06:58 UTC, AndreasBomholtz commented on src/models/device.ts
> +    public async _createValue(params: IValue): Promise<Value> {
This should still be private.

2022-04-25 06:58 UTC, AndreasBomholtz commented on test/device.test.ts
> +            },
We can't change the interface for creating values.

2022-04-25 06:58 UTC, AndreasBomholtz commented on test/device.test.ts
> +            },
We can't change the interface for creating values.

2022-04-25 06:58 UTC, AndreasBomholtz commented on test/device.test.ts
> +            },
We can't change the interface for creating values.

2022-04-25 06:58 UTC, AndreasBomholtz commented on test/device.test.ts
> +            },
We can't change the interface for creating values.

2022-04-25 06:58 UTC, AndreasBomholtz commented on test/device.test.ts
> +            },
We can't change the interface for creating values.

2022-04-25 06:58 UTC, AndreasBomholtz commented on test/network.test.ts
> +            },
We can't change the interface for creating values.

2022-04-25 06:58 UTC, AndreasBomholtz commented on test/value.test.ts
> +            },
We can't change the interface for creating values.

2022-04-25 06:58 UTC, AndreasBomholtz commented on test/value.test.ts
> +            },
We can't change the interface for creating values.

2022-04-25 06:58 UTC, AndreasBomholtz commented on test/value.test.ts
> +            },
We can't change the interface for creating values.

2022-04-26 07:37 UTC, AndreasBomholtz requested changes

2022-04-26 07:37 UTC, AndreasBomholtz commented on src/models/device.ts
> +import { ValuePermission } from '../util/interfaces';
Move this include to the other include from util.

2022-04-26 07:37 UTC, AndreasBomholtz commented on test/device.test.ts
> +                }
Missing trailing comma.

2022-04-26 08:27 UTC, AndreasBomholtz approved these changes
It looks good :)

2022-04-26 09:42 UTC, closed without merging

2022-04-26 09:43 UTC, sigidagi commented
merged PR to develop branch